### ISSUE TITLE
how do i install it

### ISSUE THREAD

**Issue by Spacer543** [pawanpaudel93/tiktok-long-video#1]
i do not know how i dont really use github

**Comment by pawanpaudel93** [comment]
@Hellome5 You can install it with the command `pip install ttlv` if you have pip installed or you can also use its web-based app where you don't need to install anything. You just have to upload the videos and get the video converted to a long version. [https://longifytiktok.herokuapp.com](https://longifytiktok.herokuapp.com/)

**Comment by pawanpaudel93** [comment]
@Hellome5 are you able to use now ??
